[project]
name = "gamemanager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "kubernetes>=36.0.3",
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "pydantic-settings>=2.15.0",
    "ruff>=0.16.3",
    "uvicorn>=0.52.3",
]

[[tool.mypy.overrides]]
module = ["kubernetes.*"]
ignore_missing_imports = true
